CC=gcc
ARCH=sm_35

stream_titan: stream.cpp
	hipcc -std=c++11 -ccbin=$(CC) -arch=$(ARCH) stream.cpp -o stream_titan

.PHONY: test
test: stream_titan
	$(shell pwd)/stream_titan

.PHONY: clean
clean:
	rm -vf stream_titan
